import * as Papa from 'papaparse';

// TODO: Dynamically load this file
const csv = `"Quest Name", "Question", "Package name", "Default Priority", "Wiki Order", "SVG Icon URL"
,,,,,
"???", "How many bikes can be parked here?", "bike_parking_capacity", "???", 1, "???"
"???", "Do you have to pay to park a bike here?", "parking_fee", "???", 5, "???"
"???", "Is there a working bicycle pump available for everyone here?", "air_pump", "???", 6, "???"
"???", "Can you pump gas yourself here?", "fuel_service", "???", 16, "???"
"???", "What’s the reference number of this stop?", "bus_stop_ref", "???", 21, "???"
"???", "How many lanes for cars does this road have?", "lanes", "???", 46, "???"
"???", "What’s the width of this road here?", "width", "???", 47, "???"
"???", "Does this road have a shoulder?", "shoulder", "???", 48, "???"
"???", "What’s the surface of the cycleway here?", "surface", "???", 53, "???"
"???", "What’s the surface of the footway here?", "surface", "???", 54, "???"
"???", "Is there a cycleway here? What type?", "cycleway", "???", 57, "???"
"???", "What’s the width of this cycleway here?", "width", "???", 58, "???"
"???", "How are the footway and cycleway laid out here?", "segregated", "???", 62, "???"
"???", "Is there any restroom here?", "toilet_availability", "???", 76, "???"
"???", "What are the collection times of this postbox?", "postbox_collection_times", "???", 83, "???"
"???", "What’s the reference number of this postbox?", "postbox_ref", "???", 84, "???"
"???", "What’s being cultivated here?", "orchard_produce", "???", 102, "???"
"???", "Is there a summit register here?", "summit_register", "???", 104, "???"
"???", "What religion is represented at this shrine?", "religion", "???", 110, "???"
"???", "Is this place air conditioned?", "air_conditioning", "???", 126, "???"
"???", "What’s the name of the bank for this ATM?", "atm_operator", "???", 129, "???"
,,,,,
"AddMemorialType", "What kind of memorial is this?", "memorial_type", 2, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/memorial.svg"
"AddBusStopRef", "What number or code identifies this stop?", "bus_stop_ref", 8, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bus_stop_name.svg"
"AddReligionToWaysideShrine", "What religion is this shrine associated with?", "religion", 27, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/religion.svg"
"AddPostboxCollectionTimes", "What are the pickup times of this collection box?", "postbox_collection_times", 48, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/mail.svg"
"AddBikeRentalType", "What type of bicycle rental is this?", "bike_rental_type", 66, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_rental.svg"
"AddBikeParkingFee", "Do you have to pay to park a bicycle here?", "parking_fee", 69, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_parking_fee.svg"
"AddBikeRentalCapacity", "How many rental bicycle spaces are here?", "bike_rental_capacity", 70, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_rental_capacity.svg"
"AddBikeParkingCapacity", "How many bicycles can be parked here?", "bike_parking_capacity", 71, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_parking_capacity.svg"
"AddBicyclePump", "Is there a working bicycle pump here?", "air_pump", 80, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_pump.svg"
"AddAtmOperator", "Which bank operates this ATM?", "atm_operator", 81, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/money.svg"
"AddPostboxRef", "What’s the identification number of this collection box?", "postbox_ref", 86, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/mail_ref.svg"
"AddEntrance", "What kind of building entrance is this?", "building_entrance", 94, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/door.svg"
"AddEntranceReference", "What is signed at this entrance?", "building_entrance_reference", 95, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/door_address.svg"
"AddSummitCross", "Is there a summit cross here?", "summit", 100, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/summit_cross.svg"
"AddOrchardProduce", "What’s being grown here?", "orchard_produce", 103, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/apple.svg"
"AddAirConditioning", "Is this place air-conditioned?", "air_conditioning", 105, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/snow_poi.svg"
"AddToiletAvailability", "Is there a restroom here?", "toilet_availability", 109, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/toilets.svg"
"AddBikeRepairAvailability", "Are bicycle repair services offered here?", "bike_shop", 114, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_repair.svg"
"AddSecondHandBicycleAvailability", "Are second-hand bicycles sold here?", "bike_shop", 115, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_second_hand.svg"
"AddFuelSelfService", "Does this gas station allow self-service?", "fuel_service", 124, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/fuel_self_service.svg"
"AddCycleway", "Is there a bicycle lane or path here? What type?", "cycleway", 128, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycleway.svg"
"AddLanes", "How many car lanes does this road have?", "lanes", 129, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/street_lanes.svg"
"AddShoulder", "Does this road have a shoulder or breakdown lane?", "shoulder", 130, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/street_shoulder.svg"
"AddRoadWidth", "How wide is the road here?", "width", 131, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/street_width.svg"
"AddCyclewaySegregation", "How are the footpath and bicycle path laid out here?", "segregated", 135, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/path_segregation.svg"
"AddFootwayPartSurface", "What’s the surface of the footpath here?", "surface", 136, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/footway_surface.svg"
"AddCyclewayPartSurface", "What’s the surface of the bicycle path here?", "surface", 137, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycleway_surface.svg"
"AddCyclewayWidth", "How wide is the bicycle path here?", "width", 139, "???", "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycleway_width.svg"
"AddSummitRegister", "Is there a summit register here?", "summit", 101, 104, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/peak.svg"
,,,,,
"AddBikeParkingCover", "Is this bicycle parking covered (protected from rain)?", "bike_parking_cover", 65, 2, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_parking_cover.svg"
"AddBikeParkingType", "What type of bicycle parking is this?", "bike_parking_type", 67, 3, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_parking.svg"
"AddBikeParkingAccess", "Who is allowed to park a bicycle here? Parking may be free or paid.", "parking_access", 68, 4, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bicycle_parking_access.svg"
"AddMotorcycleParkingCapacity", "How many motorcycles can be parked here?", "motorcycle_parking_capacity", 31, 7, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/motorcycle_parking_capacity.svg"
"AddMotorcycleParkingCover", "Is this motorcycle parking covered (protected from rain)?", "motorcycle_parking_cover", 30, 8, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/motorcycle_parking_cover.svg"
"AddParkingType", "What kind of parking is this?", "parking_type", 19, 9, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/parking.svg"
"AddParkingAccess", "Who is allowed to park here? Parking may be free or paid.", "parking_access", 20, 10, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/parking_access.svg"
"AddParkingFee", "Do you have to pay to park here?", "parking_fee", 21, 11, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/parking_fee.svg"
"AddChargingStationOperator", "Who is the operator of this charging station?", "charging_station_operator", 84, 12, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/car_charger.svg"
"AddChargingStationCapacity", "How many cars can be charged here at the same time?", "charging_station_capacity", 83, 13, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/car_charger_capacity.svg"
"AddCarWashType", "What kind of car wash is this?", "car_wash_type", 11, 14, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/car_wash.svg"
"AddTrafficCalmingType", "What type of traffic calming is this?", "traffic_calming_type", 22, 15, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/car_bumpy.svg"
"AddAirCompressor", "Is there an air compressor available here?", "air_pump", 32, 17, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/car_air_compressor.svg"
"AddBenchStatusOnBusStop", "Is there a bench at this stop?", "bus_stop_bench", 4, 18, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bench_public_transport.svg"
"AddBusStopShelter", "Is there a shelter at this stop?", "bus_stop_shelter", 3, 19, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bus_stop_shelter.svg"
"AddBusStopName", "What’s the name of this stop?", "bus_stop_name", 7, 20, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bus_stop_name.svg"
"AddBusStopLit", "Is this stop lit?", "bus_stop_lit", 9, 22, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bus_stop_lit.svg"
"AddBinStatusOnBusStop", "Is there a waste basket at this stop?", "bus_stop_bin", 5, 23, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bin_public_transport.svg"
"AddTactilePavingBusStop", "Does this stop have tactile paving?", "tactile_paving", 6, 24, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/blind_bus.svg"
"AddTactilePavingCrosswalk", "Does this crosswalk have tactile paving on both sides?", "tactile_paving", 41, 25, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/blind_pedestrian_crossing.svg"
"AddCrossing", "Are there curbs where this way meets this road here? What kind?", "crossing", 38, 26, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/pedestrian.svg"
"AddCrossingType", "What kind of crossing is this?", "crossing_type", 40, 27, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/pedestrian_crossing.svg"
"AddCrossingIsland", "Does this pedestrian crossing have an island?", "crossing_island", 39, 28, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/pedestrian_crossing_island.svg"
"AddTrafficSignalsButton", "Do these traffic lights have a button to request a walk signal?", "traffic_signals_button", 43, 29, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/traffic_lights.svg"
"AddTrafficSignalsSound", "Are there sound signals for the blind here?", "traffic_signals_sound", 42, 30, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/blind_traffic_lights_sound.svg"
"AddTrafficSignalsVibration", "Do these traffic lights have a tactile indication for blind people for when it’s safe to cross?", "traffic_signals_vibrate", 44, 31, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/blind_traffic_lights.svg"
"AddMaxSpeed", "What’s the speed limit for this street?", "max_speed", 140, 32, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/max_speed.svg"
"AddOneway", "Is this a one-way street? In which direction?", "oneway", 92, 33, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/oneway.svg"
"AddSuspectedOneway", "Is this a one-way street?", "oneway_suspects", 93, 34, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/oneway.svg"
"AddMaxHeight", "What is the height limit here?", "max_height", 89, 35, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/max_height.svg"
"AddMaxPhysicalHeight", "What is the height limit here?", "max_height", 90, 36, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/max_height_measure.svg"
"AddMaxWeight", "What’s the weight limit here?", "max_weight", 88, 37, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/max_weight.svg"
"AddBollardType", "What type of bollard is this?", "bollard_type", 57, 38, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/no_cars.svg"
"AddBicycleBarrierType", "What type of bicycle barrier is this?", "barrier_bicycle_barrier_type", 54, 39, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/no_bicycles.svg"
"AddBarrierType", "What type of barrier is this?", "barrier_type", 51, 40, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/barrier.svg"
"AddBarrierOnPath", "How does this path cross the barrier here?", "barrier_type", 52, 41, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/barrier_on_path.svg"
"AddBarrierOnRoad", "How does this road cross the barrier here?", "barrier_type", 53, 42, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/barrier_on_road.svg"
"AddStileType", "What type of stile is this?", "barrier_type", 55, 43, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/no_cow.svg"
"AddRailwayCrossingBarrier", "What barriers are used at this railway crossing?", "railway_crossing", 10, 44, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/railway.svg"
"AddRoadName", "What’s the name of this street?", "road_name", 91, 45, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/street_name.svg"
"AddRoadSurface", "What surface does this piece of road have?", "surface", 126, 49, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/street_surface.svg"
"AddRoadSmoothness", "What’s the surface quality of this road here?", "smoothness", 132, 50, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/street_surface_detail.svg"
"AddPathSurface", "What’s the surface here?", "surface", 134, 51, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/way_surface.svg"
"AddPathSmoothness", "What’s the surface quality here?", "smoothness", 133, 52, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/way_surface_detail.svg"
"AddTracktype", "What’s the surface firmness of this track?", "tracktype", 127, 55, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/tractor.svg"
"AddWayLit", "Is it lit here?", "way_lit", 145, 56, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/lantern.svg"
"AddProhibitedForPedestrians", "Are pedestrians forbidden to walk on this road here?", "foot", 98, 59, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/no_pedestrians.svg"
"AddSidewalk", "Does this street have a sidewalk?", "sidewalk", 125, 60, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/sidewalk.svg"
"AddSidewalkSurface", "What’s the surface of the sidewalk here?", "surface", 138, 61, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/sidewalk_surface.svg"
"AddBuildingType", "What kind of building is this?", "building_type", 141, 63, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/building.svg"
"AddIsBuildingUnderground", "Is this building completely underground?", "building_underground", 29, 64, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/building_underground.svg"
"AddBuildingLevels", "How many levels above the basement does this building have?", "building_levels", 142, 65, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/building_levels.svg"
"AddRoofShape", "What basic shape does this building’s roof have?", "roof_shape", 143, 66, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/roof_shape.svg"
"AddHousenumber", "What’s the house number of this building?", "address", 72, 67, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/housenumber.svg"
"AddAddressStreet", "What street is this on?", "address", 73, 68, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/housenumber_street.svg"
"MarkCompletedHighwayConstruction", "Is this way completed?", "construction", 99, 69, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/road_construction.svg"
"MarkCompletedBuildingConstruction", "Is this building completed?", "construction", 15, 70, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/building_construction.svg"
"AddWheelchairAccessBusiness", "Is this place wheelchair accessible?", "wheelchair_access", 120, 71, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/wheelchair_shop.svg"
"AddWheelchairAccessPublicTransport", "Is this place wheelchair accessible?", "wheelchair_access", 107, 72, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/wheelchair.svg"
"AddWheelchairAccessOutside", "Is this place wheelchair accessible?", "wheelchair_access", 87, 73, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/toilets_wheelchair.svg"
"AddWheelchairAccessToilets", "Is this place wheelchair accessible?", "wheelchair_access", 113, 74, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/toilets_wheelchair.svg"
"AddWheelchairAccessToiletsPart", "Is the restroom at this place wheelchair accessible?", "wheelchair_access", 112, 75, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/toilets_wheelchair.svg"
"AddToiletsFee", "Do you have to pay to use this restroom?", "toilets_fee", 110, 77, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/toilet_fee.svg"
"AddBabyChangingTable", "Does this place have a baby changing table?", "baby_changing_table", 111, 78, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/baby.svg"
"AddSport", "What sport is played here?", "sport", 16, 79, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/sport.svg"
"AddPlaygroundAccess", "Who is allowed to use this playground?", "playground_access", 47, 80, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/playground.svg"
"AddPitchSurface", "What’s the surface here?", "surface", 17, 81, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/pitch_surface.svg"
"AddPitchLit", "Is it lit here?", "pitch_lit", 18, 82, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/pitch_lantern.svg"
"AddPostboxRoyalCypher", "What’s the royal cypher on this postbox?", "postbox_royal_cypher", 85, 85, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/crown.svg"
"AddPoliceType", "Which type of police station is this?", "police_type", 46, 86, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/police.svg"
"AddRecyclingType", "What type of recycling facility is this?", "recycling", 33, 87, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/recycling.svg"
"AddRecyclingContainerMaterials", "What can be left here for recycling?", "recycling_material", 35, 88, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/recycling_container.svg"
"DetermineRecyclingGlass", "Can only glass bottles and jars be recycled here, or any type of glass?", "recycling_glass", 34, 89, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/recycling_glass.svg"
"AddClothingBinOperator", "Who accepts donations for this clothing bin?", "clothing_bin_operator", 82, 90, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/recycling_clothes.svg"
"AddGeneralFee", "Do you need to pay to enter here?", "general_fee", 59, 91, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/fee.svg"
"AddPowerPolesMaterial", "What’s this pole made of?", "powerpoles_material", 28, 92, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/power.svg"
"AddBridgeStructure", "What’s the structure of this bridge?", "bridge_structure", 14, 93, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bridge.svg"
"AddFireHydrantType", "What kind of fire hydrant is this?", "fire_hydrant", 62, 94, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/fire_hydrant.svg"
"AddFireHydrantDiameter", "What diameter is specified on the sign for this fire hydrant?", "fire_hydrant_diameter", 64, 95, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/fire_hydrant_diameter.svg"
"AddFireHydrantPosition", "Where is this fire hydrant located?", "fire_hydrant_position", 63, 96, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/fire_hydrant_grass.svg"
"AddIsDefibrillatorIndoor", "Is this defibrillator (AED) inside a building?", "defibrillator", 108, 97, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/defibrillator.svg"
"AddSelfServiceLaundry", "Does this laundry provide self-service?", "self_service", 58, 98, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/laundry.svg"
"AddFerryAccessPedestrian", "Does this ferry route transport pedestrians?", "ferry", 96, 99, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/ferry_pedestrian.svg"
"AddFerryAccessMotorVehicle", "Does this ferry route transport motor vehicles?", "ferry", 97, 100, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/ferry.svg"
"AddDrinkingWater", "Is the water potable here?", "drinking_water", 60, 101, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/drinking_water.svg"
"AddForestLeafType", "Do the trees here have needles or leaves?", "leaf_detail", 102, 103, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/leaf.svg"
"AddPicnicTableCover", "Is this picnic table covered (protected from rain)?", "picnic_table_cover", 13, 105, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/picnic_table_cover.svg"
"AddBenchBackrest", "Does this bench have a backrest?", "bench_backrest", 12, 106, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/bench_poi.svg"
"AddInformationToTourism", "What type of tourist information is this?", "tourism_information", 45, 107, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/information.svg"
"AddBoardType", "What’s the topic of this information board?", "board_type", 50, 108, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/board_type.svg"
"AddReligionToPlaceOfWorship", "What religion is practiced at this place?", "religion", 26, 109, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/religion.svg"
"AddStepCountStile", "How many steps are here?", "step_count", 56, 111, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/steps_count_brown.svg"
"AddStepCount", "How many steps are here?", "step_count", 144, 112, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/steps_count.svg"
"AddHandrail", "Do these steps have a handrail?", "handrail", 23, 113, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/steps_handrail.svg"
"AddStepsRamp", "Do these steps have a ramp? What kind?", "steps_ramp", 24, 114, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/steps_ramp.svg"
"AddStepsIncline", "Which direction leads upwards for these steps?", "steps_incline", 25, 115, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/steps.svg"
"AddTactilePavingKerb", "Is there tactile paving on this curb here?", "tactile_paving", 37, 116, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/kerb_tactile_paving.svg"
"AddKerbHeight", "What’s the height of this curb?", "kerb_height", 36, 117, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/kerb_type.svg"
"AddOpeningHours", "What are the opening hours here?", "opening_hours", 78, 118, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/opening_hours.svg"
"CheckOpeningHoursSigned", "Are the opening hours here signed?", "opening_hours_signed", 74, 119, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/opening_hours_signed.svg"
"AddVegetarian", "Any vegetarian items on the menu here?", "diet_type", 116, 120, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/restaurant_vegetarian.svg"
"AddVegan", "Any vegan items on the menu here?", "diet_type", 117, 121, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/restaurant_vegan.svg"
"AddKosher", "Are kosher products offered here?", "diet_type", 119, 122, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/kosher.svg"
"AddHalal", "Are halal products offered here?", "diet_type", 118, 123, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/halal.svg"
"AddSeating", "What kind of seating does this place have?", "seating", 79, 124, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/seating.svg"
"AddInternetAccess", "What kind of internet connection does this place offer?", "internet_access", 121, 125, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/wifi.svg"
"AddPlaceName", "What’s the name of this place?", "place_name", 77, 127, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/label.svg"
"AddLevel", "On which level number is this place located?", "level", 104, 128, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/level.svg"
"AddCameraType", "What type of surveillance camera is this?", "camera_type", 61, 130, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/surveillance_camera.svg"
"AddAcceptsCash", "Is cash payment accepted here?", "accepts_cash", 123, 131, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/cash.svg"
"AddAcceptsCards", "Are credit or debit cards accepted here?", "accepts_cards", 122, 132, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/card.svg"
"AddSmoking", "Is smoking allowed here?", "smoking", 106, 133, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/smoking.svg"
"SpecifyShopType", "What type of shop is this?", "shop_type", 75, 134, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/check_shop.svg"
"CheckShopType", "This shop has been vacant. What’s here now?", "shop_type", 76, 135, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/check_shop.svg"
"CheckExistence", "Is this still here?", "existence", 49, 136, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/check.svg"
"OsmNoteQuest", "Can you contribute anything to this note?", "note_discussion", 1, 137, "https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/res/graphics/quest/notes.svg"`;

// TODO: Fix header bugs
// Parse the CSV into an object
const parsedCsv = Papa.parse(csv);

export function getStreetCompleteDetails(quest: string): string | null {
	console.log(parsedCsv.data);
	console.log(quest);
	const questDetails = parsedCsv.data.find((item) => item[0] === quest);
	console.log(questDetails);
	if (questDetails) {
		console.log(questDetails[5].substr(2, questDetails[5].length - 3));
		return questDetails[5].substr(2, questDetails[5].length - 3);
	}
	return null;
}
