services:
  app:
    build: .
    image: ghcr.io/wjtje/wjtje.dev:latest
    restart: unless-stopped
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      - DATABASE_URL=postgresql://postgres:example@database:5432/postgres?schema=public
      - OSM_USERNAME=name
      - GITHUB_USERNAME=name
      - GITHUB_TOKEN=token with public repo access
      - BASE_URL=https://name.io/
      - CACHE_DURATION=10
      - IGNORED_REPOS=["name","name.github.io"]

  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
